# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
    aws-ecr: circleci/aws-ecr@7.0.0
    aws-ecs: circleci/aws-ecs@1.0.1
    aws-s3: circleci/aws-s3@1.0.11
    aws-cli: circleci/aws-cli@0.1.13

jobs:
  checkout:
        docker:
            - image: circleci/python:3-stretch-browsers
        steps:
            - checkout:
                  path: ~/team_4
            - persist_to_workspace:
                  root: ~/team_4
                  paths:
                      - .
  push_image_enudge:
        docker:
            - image: circleci/node:10
        working_directory: ~/team_4
        steps:
            - attach_workspace:
                  at: ~/team_4
            - setup_remote_docker:
                  docker_layer_caching: false
            - aws-ecr/build-and-push-image:
                  checkout: false
                  repo: "enudge-app"
                  dockerfile: Dockerfile
                  tag: ${CIRCLE_SHA1}
                  account-url: "122068508766"
                  aws-access-key-id: "AKIARY26ZUBPDPUNI6HS"
                  aws-secret-access-key: "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"
                  region: "us-west-2"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
        - checkout:
            filters:
                branches:
                    only:
                        - main
        - push_image_enudge:
            requires:
                - checkout

